### ISSUE TITLE
Can I please get a world file?

### ISSUE THREAD

**Issue by bubzilla** [honkling/PrisonGame#21]
This might sound weird but I need the server world for my own server.

**Comment by bubzilla** [comment]
Wait how do I assign a label.

**Comment by lilrosalyn** [comment]
we don't need two exact copies of PrisonButBad running around

**Comment by bubzilla** [comment]
Ok :(.

**Comment by bubzilla** [comment]
Though it would make sense to remove the coordinates from the prisons file if the world won't be available.

**Comment by lilrosalyn** [comment]
the prisons file is configurable, modify it to use your own maps :p
